version: "3.8"

volumes:
  mysql_data:
    driver: local

services:
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - .rabbitmq_data/:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3307:3307

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KK_TO_RMQ_URL: localhost
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: empty
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: guest
      KK_TO_RMQ_PASSWORD: guest
    ports:
      - 8080:8080
    depends_on:
      - mysql
